apiVersion: v1
kind: Service
metadata:
  name: attendancesapp-service
spec:
  type: NodePort
  selector:
    app: attendancesapp
  ports:
    - port: 8676
      targetPort: 8676
      nodePort: 30077

